module.exports = {
  rules: {
    'array-bracket-spacing': 2,
    'arrow-body-style': [2, 'as-needed'],
    'arrow-parens': [2, 'as-needed'],
    'brace-style': [2, '1tbs', { 'allowSingleLine': true }],
    'camelcase': [2, { 'properties': 'never' }],
    'comma-dangle': [1, 'never'],
    'comma-spacing': [2, { 'before': false, 'after': true }],
    'comma-style': [2, 'last'],
    'constructor-super': 2,
    'eol-last': 2,
    'indent': [2, 2],
    'jsx-quotes': 2,
    'key-spacing': [2, { 'beforeColon': false, 'afterColon': true }],
    'max-depth': [2, 4],
    'max-len': [2, 120, 4],
    'max-params': [2, 4],
    'max-statements': [2, 10],
    'newline-before-return': 2,
    'no-bitwise': 2,
    'no-class-assign': 2,
    'no-cond-assign': [2, 'always'],
    'no-confusing-arrow': [2, { 'allowParens': true }],
    'no-const-assign': 2,
    'no-constant-condition': 2,
    'no-dupe-class-members': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 2,
    'no-extra-bind': 2,
    'no-extra-boolean-cast': 2,
    'no-extra-semi': 2,
    'no-fallthrough': 2,
    'no-mixed-spaces-and-tabs': 2,
    'no-multi-spaces': 2,
    'no-multiple-empty-lines': [2, { 'max': 1 }],
    'no-nested-ternary': 2,
    'no-new-object': 2,
    'no-redeclare': 2,
    'no-self-assign': 2,
    'no-sequences': 2,
    'no-sparse-arrays': 2,
    'no-this-before-super': 2,
    'no-trailing-spaces': 2,
    'no-unexpected-multiline': 2,
    'no-unreachable': 2,
    'no-unused-vars': [2, { 'vars': 'all', 'args': 'none' }],
    'object-curly-spacing': [2, 'always', { 'objectsInObjects': false }],
    'object-shorthand': [2, 'always'],
    'prefer-const': 2,
    'quotes': [2, 'single'],
    'semi': [2, 'always'],
    'use-isnan': 2,
    'valid-typeof': 2
  }
};
